// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qniknepsjvkdbitnztki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuaWtuZXBzanZrZGJpdG56dGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDAzNzEsImV4cCI6MjA2NTkxNjM3MX0.nGIfIyMEg_evJNCo-iPNDTq1FUzPo9ahGPd8G3Vsncs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);